server:
  port: 8082
spring:
  mail:
    protocol: smtp #邮件协议
    host: smtp.163.com  #网易邮箱smtp服务器地址
    port: 25
    username: 15392623941@163.com #发件人邮箱地址
    password: LTJESVQRRPSWAUAX #授权码
    default-encoding: utf-8 #编码字符集

  rabbitmq:
    username: admin
    password: admin
    host: 192.168.10.64
    port: 5672
    virtual-host: /
    connection-timeout: 0
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 192.168.10.10
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    password:
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
